MyBusiness.WebApp/Controllers/BrandController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyBusiness.DataAccess;
using MyBusiness.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyBusiness.WebApp.Controllers
{
    public class BrandController : Controller
    {
        //  https://github.com/bhrugen/Uplift/blob/master/Uplift/Areas/Admin/Controllers/CategoryController.cs

        private IDataRepository _data_repository; 
        public BrandController(IDataRepository data_repository)
        {
           _data_repository = data_repository;
        }
        
        //  The main Get  
        public ActionResult Index()
        {
            return View( _data_repository.Brand.GetAll());
        }

        //  Update and Insert  Action 
        //  if id is null => Insert 
        //        else    => Insert
        public IActionResult Upsert(int? id) {
            Brand brand = new Brand();
            if (id == null)
            {
                return View(brand);
            }
            brand = _data_repository.Brand.GetById(id.GetValueOrDefault());
            if (brand == null)
            {
                return NotFound();
            }
            return View(brand);
        }

        //  Post 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Brand brand )
        {
            if (ModelState.IsValid)
            {
                if (brand.BrandId == 0)
                {
                    // _unitOfWork.Category.Add(category);
                    _data_repository.Brand.AddNew(brand, "insert user");
                }
                else
                {
                    //  _unitOfWork.Category.Update(category);
                    _data_repository.Brand.Update(brand, "user update");
                }
                return RedirectToAction(nameof(Index));
            }
            return View(brand);
        }

        #region APIs
        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _data_repository.Brand.GetAll() });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            int rows_deleted = _data_repository.Brand.Delete(id);
            if ( rows_deleted == 0 )
            {
                return Json(new { success = false, message = "Error while deleting." });
            }
            return Json(new { success="true" , message="Delete successfully." });
        }

        #endregion
    }
}

/*
        // GET: BrandController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: BrandController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Brands/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BrandName")] Brand brand)
        {
            if (ModelState.IsValid)
            {
                int i = _data_repository.Brand.AddNew(brand, "raul");
                // await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(brand);
        }

        // GET: BrandController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: BrandController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        //// GET: BrandController/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        // POST: BrandController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
*/

MyBusiness.WebApp/Controllers/InsuranceController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyBusiness.DataAccess;
using MyBusiness.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyBusiness.WebApp.Controllers
{
    public class InsuranceController : Controller
    {

        private IDataRepository _data_repository;
        public InsuranceController(IDataRepository data_repository)
        {
            _data_repository = data_repository;
        }
        // GET: InsuranceController
        public ActionResult Index()
        {
            return View(_data_repository.Insurances.GetAll());
        }

        //  Update and Insert  Action 
        //  if id is null => Insert 
        //        else    => Insert
        public IActionResult Upsert(int? id)
        {
            Insurance insurance = new Insurance();
            if (id == null)
            {
                return View(insurance);
            }
            insurance = _data_repository.Insurances.GetById(id.GetValueOrDefault());
            if (insurance == null)
            {
                return NotFound();
            }
            return View(insurance);
        }

        //  Post 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Insurance insurance)
        {
            if (ModelState.IsValid)
            {
                if (insurance.InsuranceId == 0)
                {
                    // _unitOfWork.Category.Add(category);
                    _data_repository.Insurances.AddNew(insurance, "insert user");
                }
                else
                {
                    //  _unitOfWork.Category.Update(category);
                    _data_repository.Insurances.Update(insurance, "user update");
                }
                return RedirectToAction(nameof(Index));
            }
            return View(insurance);
        }


        // POST: InsuranceController/Delete/5
        #region APIs
        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _data_repository.Insurances.GetAll() });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            int rows_deleted = _data_repository.Insurances.Delete(id);
            if (rows_deleted == 0)
            {
                return Json(new { success = false, message = "Error while deleting." });
            }
            return Json(new { success = "true", message = "Delete successfully." });
        }


        #endregion
    }
}

MyBusiness.WebApp/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using MyBusiness.DataAccess;
using MyBusiness.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyBusiness.WebApp.Controllers
{

    public class ProductController : Controller
    {
        private IDataRepository _data_repository;
        public ProductController(IDataRepository data_repository)
        {
            _data_repository = data_repository;
        }
        public IActionResult Index()
        {
            return View(_data_repository.Products.GetAll());
        }


        //  Update and Insert  Action 
        //  if id is null => Insert 
        //        else    => Insert
        public IActionResult Upsert(int? id)
        {
            Product product = new Product();
            if (id == null)
            {
                return View(product);
            }
            product = _data_repository.Products.GetById(id.GetValueOrDefault());
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }


        //  Post 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Product product)
        {
            if (ModelState.IsValid)
            {
                if (product.ProductId == 0)
                {
                    // _unitOfWork.Category.Add(category);
                    _data_repository.Products.AddNew(product, "insert user");
                }
                else
                {
                    //  _unitOfWork.Category.Update(category);
                    _data_repository.Products.Update(product, "user update");
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        #region APIs
        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _data_repository.Products.GetAll() });
        }

        /// <summary>
        ///   Deletes a Product
        /// </summary>
        /// <param name="id">Product Id</param>
        /// <returns></returns>
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            int rows_deleted = _data_repository.Products.Delete(id); // <--
            if (rows_deleted == 0)
            {
                return Json(new { success = false, message = "Error while deleting." });
            }
            return Json(new { success = "true", message = "Delete successfully." });
        }

        #endregion
    }
}

MyBusiness.WebApp/Controllers/SupplierController.cs
using Microsoft.AspNetCore.Mvc;
using MyBusiness.DataAccess;
using MyBusiness.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyBusiness.WebApp.Controllers
{
    public class SupplierController : Controller
    {
        private IDataRepository _data_repository;
        public SupplierController(IDataRepository data_repository)
        {
            _data_repository = data_repository;
        }
        public IActionResult Index()
        {
            return View(_data_repository.Suppliers.GetAll());
        }

        //  Update and Insert  Action 
        //  if id is null => Insert 
        //        else    => Insert
        public IActionResult Upsert(int? id)
        {
           Supplier supplier = new Supplier();
            if (id == null)
            {
                return View(supplier);
            }
            supplier = _data_repository.Suppliers.GetById(id.GetValueOrDefault());
            if (supplier == null)
            {
                return NotFound();
            }
            return View(supplier);
        }

        //  Post 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                if (supplier.SupplierId == 0)
                {
                    // _unitOfWork.Category.Add(category);
                    _data_repository.Suppliers.AddNew(supplier, "insert user");
                }
                else
                {
                    //  _unitOfWork.Category.Update(category);
                    _data_repository.Suppliers.Update(supplier, "usert update");
                }
                return RedirectToAction(nameof(Index));
            }
            return View(supplier);
        }

        #region APIs

        [HttpGet]
            public IActionResult GetAll()
            {
                return Json(new { data = _data_repository.Suppliers.GetAll() });
            }

        /// <summary>
        ///   Deletes a Supplier
        /// </summary>
        /// <param name="id">Product Id</param>
        /// <returns></returns>
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            int rows_deleted = _data_repository.Suppliers.Delete(id); // <--
            if (rows_deleted == 0)
            {
                return Json(new { success = false, message = "Error while deleting." });
            }
            return Json(new { success = "true", message = "Delete successfully." });
        }

        #endregion
    }
}

MyBusiness.WebApp/Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control">Create</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

MyBusiness.WebApp/Views/Shared/_EditAndBackToListButton.cshtml
@model int

<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control" asp-route-id="@Model">Update</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

MyBusiness.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyBusiness.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Clear Route Auto Glass</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ServiceOrders" asp-action="Create">Request new service</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Work</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="" asp-controller="serviceorders" asp-action="Index">Services Orders</a>
                                <div class="dropdown-divider"></div>
                                <a class="nav-link text-dark" asp-area="" asp-controller="UserManager" asp-action="Index">User Manager</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Administrator</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="" asp-controller="Brand" asp-action="Index">Brands</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Insurance" asp-action="Index">Insurances</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Supplier" asp-action="Index">Suppliers</a>
                                <a class="dropdown-item" asp-area="" asp-controller="ServiceOrderStatus" asp-action="Index">Service Order Status</a>


                                <div class="dropdown-divider"></div>
                                <a class="nav-link text-dark" asp-area="" asp-controller="UserManager" asp-action="Index">User Manager</a>
                            </div>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MyBusiness.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.serializeJSON/2.9.0/jquery.serializejson.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/e19c476714.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>